language: python

dist: trusty

sudo: false

cache: apt

addons:
    apt:
        packages:
            - build-essential
            - g++
            - mpich2
            - libmpich2-dev
            - libhdf5-7
            - libhdf5-mpich-dev
            - gfortran
            - hdf5-tools

python:
    - 2.7
    - 3.4

env:
    # try all python versions with the latest stable Numpy
    - NUMPY_VERSION=1.9 ASTROPY_VERSION=1.0 SETUP_CMD='test' YT_VERSION=3

matrix:

    include:

        # try older Numpy and yt version
        - python: 2.7
          env: NUMPY_VERSION=1.8 ASTROPY_VERSION=0.4 SETUP_CMD='test' YT_VERSION=2

        # try old Python version
        - python: 2.6
          env: NUMPY_VERSION=1.8 ASTROPY_VERSION=0.4 SETUP_CMD='test' YT_VERSION=None

before_install:

   # Python packages
   - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
   - chmod +x miniconda.sh
   - ./miniconda.sh -b
   - export PATH=/home/travis/miniconda/bin:$PATH
   - conda update --yes conda

   # Make sure that interactive matplotlib backends work
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   
   # Add path for hyperion binaries
   - export PATH=$HOME/usr/bin:$PATH

install:
   - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
   - source activate test
   - if [[ $YT_VERSION == None ]];
     then
       conda install --yes numpy=$NUMPY_VERSION h5py astropy=$ASTROPY_VERSION pip matplotlib;
     else
       conda install --yes numpy=$NUMPY_VERSION h5py astropy=$ASTROPY_VERSION pip matplotlib yt=$YT_VERSION;
     fi

script:
   - ./configure --prefix=$HOME/usr
   - make serial
   - make install
   - python setup.py install  # to get the hyperion script installed
   - python setup.py $SETUP_CMD
