language: c

os:
  - linux
  - osx

osx_image: beta-xcode6.1

env:
    global:
        - SETUP_XVFB=True
        - CONDA_CHANNELS='conda-forge'
        - CONDA_DEPENDENCIES='numpy astropy h5py matplotlib yt mpich hdf5 gcc'
        - SETUP_CMD='test'
    matrix:
        - PYTHON_VERSION=2.7
        - PYTHON_VERSION=3.4
        - PYTHON_VERSION=3.5
        - PYTHON_VERSION=3.6

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - export DYLD_FALLBACK_LIBRARY_PATH=$HOME/miniconda/envs/test/lib

script:
   - ./configure
   - make serial
   - sudo make install
   - python setup.py install  # to get the hyperion script installed
   - python setup.py $SETUP_CMD
